# Generated by Django 5.0.1 on 2024-02-13 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_staff_password'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='staff',
            new_name='Staff_Model',
        ),
    ]
