# Generated by Django 5.0.1 on 2024-02-13 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_alter_services_price'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='services',
            new_name='Services_Model',
        ),
    ]
