# Generated by Django 5.0.1 on 2024-02-14 08:09

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('total', models.IntegerField()),
                ('discount', models.IntegerField(default=0)),
                ('tax', models.IntegerField(default=0)),
                ('grand_total', models.IntegerField()),
                ('Appointment_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appointment.appointment', verbose_name='Appointment')),
            ],
        ),
    ]
