# Generated by Django 5.0.1 on 2024-02-12 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_name', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=6)),
                ('martial_status', models.CharField(choices=[('UnMarried', 'Unmarried'), ('Married', 'Married')], max_length=9)),
                ('phone_no', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=150)),
                ('blood_group', models.CharField(choices=[('A+', 'A Positive'), ('A-', 'A Negative'), ('B+', 'B Positive'), ('B-', 'B Negative'), ('O+', 'O Positive'), ('O-', 'O Negative'), ('AB+', 'Ab Positive'), ('AB-', 'Ab Negative')], max_length=4)),
            ],
        ),
    ]
